### ISSUE TITLE
[BUG]: Password Visibility Toggle Not Functioning

### ISSUE THREAD

**Issue by ashwaniMaddheshiya** [Multiwoven/multiwoven-ui#100]
## Description
The password visibility toggle feature, which allows users to reveal or hide the entered password text in Login & SignUp screen, is not functioning as expected. 

## Expected Behavior
It should reveal or hide the password alternatively on clicking the icon.

## Actual Behavior
When attempting to toggle the visibility of the password text by clicking on the icon, the password remains obscured and does not change to plain text.

**Comment by UtkarshDixit-py** [comment]
@ashwaniMaddheshiya will you be working on this issue? if not i can take this up. just let me know.

**Comment by ashwaniMaddheshiya** [comment]
@UtkarshDixit-py I am working on this issue.

**Comment by sumitd94** [comment]
@ashwaniMaddheshiya this is already fixed. you will be able to see this change in the upcoming release.

**Comment by ashwaniMaddheshiya** [comment]
@sumitd94 oh thanks for the update.
