### ISSUE TITLE
[FEATURE]: Design custom toast component

### ISSUE THREAD

**Issue by sumitd94** [Multiwoven/multiwoven-ui#77]
## Description

Currently, we are using the [toast component](https://chakra-ui.com/docs/components/toast) which is being provided by chakra UI.

We still want to use that toast component but with custom styles for which we will have to render our [custom component](https://chakra-ui.com/docs/components/toast#custom-component)

Below are the specs for the custom component:

> you can go through the [chakra config file](https://github.com/Multiwoven/multiwoven-ui/blob/main/src/chakra.config.ts) to understand how the design tokens are setup

The toast can have different variants

- Success
- Error
- Warning
- Info

Structure the component in a way, that it accepts the configuration and returns the type of toast we want to render.
A sample specification for a success component is defined below:

## Success Component

<img width="767" alt="Screenshot 2024-02-27 at 1 07 36 AM" src="https://github.com/Multiwoven/multiwoven-ui/assets/29303618/46e16386-f276-49ff-bfa9-aa1af8aea574">

### Specification for the Text Component

- use the size token as `sm`
- use the fontWeight as `semibold`

### Specification for the Box

- for background color, use the token: `success.100`
- for the box border: `1px solid`, and token for border color: `success.200`
- box will be of fixed width: `400px`
- PaddingX: `16px`, PaddingY: `20px`
- border radius: `8px`

### Specification for the icons

- for the cross icon, use the color token - `black.100`
- The icons will be of fixed height and width of `20px`
- The color token for tick icon will be - `success.400`

**Comment by suryaraj1** [comment]
Hi. I am interested in working on this. Could you please assign this to me. 😀

**Comment by Maianki** [comment]
Hi, would love to work on this. Can you assign this to me?

**Comment by pramod8095** [comment]
Hi, would love to work on this. Can you assign this to me?

**Comment by HanikJain** [comment]
Hey, I would like to work on this issue can you please assign it to me?

**Comment by HanikJain** [comment]
Hey, I would like more visibility on this. Should it be a custom hook, like replacing the current useToast with useCustomToast and passing custom config to render the custom component? Alternatively, should I design a custom toast component that will be added to the current toast function, for example: `toast({ render: () => (<CustomToast />) })`?

**Comment by ice-rahul** [comment]
@sumitd94, you should even attach figma file for the desired design

**Comment by suryaraj1** [comment]
@sumitd94  I have a question which is inline to @HanikJain 's doubt. Should I go about creating a custom hook or a component which can be rendered using the `render` prop in `Toast` from chakra?

**Comment by sumitd94** [comment]
> @sumitd94 I have a question which is inline to @HanikJain 's doubt. Should I go about creating a custom hook or a component which can be rendered using the `render` prop in `Toast` from chakra?

@HanikJain @suryaraj1 Either which way works, making a custom hook makes more sense here.

**Comment by HanikJain** [comment]
@sumitd94 I have added custom hook implementation in my [PR](https://github.com/Multiwoven/multiwoven-ui/pull/83). Currently, I have only implemented it in SignIn.tsx. Please review the code structure and let me know if any changes are required

**Comment by sumitd94** [comment]
> @sumitd94 I have added custom hook implementation in my [PR](https://github.com/Multiwoven/multiwoven-ui/pull/83). Currently, I have only implemented it in SignIn.tsx. Please review the code structure and let me know if any changes are required

@HanikJain I appreciate you raising a draft PR, but this issue is assigned to @suryaraj1 .
Can you both please coordinate on this on our public slack channel or how ever it works.

**Comment by suryaraj1** [comment]
Hi @sumitd94. Due to some personal exigency, would not be able to allocate time for this issue. Would make sense to un-assign this from me. Thanks. :smile:

**Comment by sumitd94** [comment]
@HanikJain Assigning this to you.
