### ISSUE TITLE
[BUG]: The "Show/Hide Password" functionality is not working as expected in the password field.

### ISSUE THREAD

**Issue by vijaytalviya** [Multiwoven/multiwoven-ui#88]
## Description
On the sign-in and sign-up pages, when entering a password and clicking the eye icon to reveal it, the password remains obscured.

## Steps to Reproduce
1. Navigate to the sign-in page.
2. Enter the password.
3. Click the eye icon.

## Expected Behavior
The password should become visible when clicking the eye icon.

## Current Behavior
The password remains obscured even after clicking the eye icon.

## Possible Solution
The `type` prop of the input field is being overridden by other props of the `HiddenInput` component. To address this, consider adding the `type` prop after spreading other props.

**Comment by sumitd94** [comment]
@vijaytalviya Thanks for raising this bug, can you please raise a PR to fix this? I will assign this to you.

**Comment by sumitd94** [comment]
Thanks for raising the issue and fixing it :)

**Comment by vijaytalviya** [comment]
You're welcome! 😊 Excited to contribute more! 🚀"
